### ISSUE TITLE
multiple containers?

### ISSUE THREAD

**Issue by aecobb53** [aecobb53/weatherman#22]
`docker-compose -f ./docker-compose.yml -f ./somewhereelse/docker-compose.yml -f ./1/2/3/docker-compose.yml up`?

**Comment by aecobb53** [comment]
https://docs.docker.com/compose/extends/

**Comment by aecobb53** [comment]
To use multiple override files, or an override file with a different name, you can use the `-f` option to specify the list of files. Compose merges files in the order they’re specified on the command line. See the `docker-compose` [command reference](https://docs.docker.com/compose/reference/overview/) for more information about using` -f`.

**Comment by aecobb53** [comment]
can have multiple Dockerfiles but they need to be in different directories

```
docker-compose.yml
docker
├── web
│   └── Dockerfile
└── db
    └── Dockerfile
```

```yaml
version: '3'
services:
  web:
    # will build ./docker/web/Dockerfile
    build: ./docker/web
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  db:
    # will build ./docker/db/Dockerfile
    build: ./docker/db
    ports:
      - "3306:3306"
  redis:
    # will use docker hub's redis prebuilt image from here:
    # https://hub.docker.com/_/redis/
    image: "redis:alpine"
```

```
# The following command will create and start all containers in the background
# using docker-compose.yml from current directory
docker-compose up -d

# get help
docker-compose --help
```

---

in case you need in the directory above
```yaml
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/code
```
